# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: db7a69f808a5d93b0d51655788c96afc4d2781cc1ed5e5dd507b0c6dc92a730349208b8ee793bb7261b5e48dabc9836325e8dbe77e49fef67e7aad0ef383c71b

test:
  secret_key_base: 5328894f251f6380b1e7818d88cccc28afe58da3ff005eca36e29d46dd83e50eb52ce5b70fc411d77634de0008897f289a3ded1bb34e1b691422791ad15fa5f7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
